### PR TITLE
config/keys: fail parsing if invalid source is set

### LINKED ISSUE #28: feature: validate keys config source.
> A clear and concise description of what you want the system to do.

Currently when getting the keys from the config in `GetKeysFromConfig` we have a switch on the `cfg.Source`:
https://github.com/greenpau/go-authcrunch/blob/ff000238985d20d12c1aed31235d6509f3f45dd1/pkg/kms/key.go#L101
If the `cfg.Source` is neither `"config"` nor `"env"` it is silently ignored. I suggest to add the following default case in `switch`:
```go
	default:
		return nil, fmt.Errorf("unsupported source: %s", cfg.Source)
```

### PR DESCRIPTION
**Pull request by lukedirtwalker**
If an invalid source is specified in the key config, the parsing will error out.

Fixes #28

### CODE REVIEW

**Comment by lukedirtwalker** [comment]
Thanks for the feedback my manager signed it in https://github.com/greenpau/go-authcrunch/pull/33 do I also need to list myself there?

**Comment by greenpau** [comment]
@lukedirtwalker , yes, please.

**Comment by lukedirtwalker** [comment]
@greenpau done.

**Review by greenpau — APPROVED** [review]

**Comment by greenpau** [comment]
@lukedirtwalker , thank you for contributing! 👍

**Pull request merged**
