### PR TITLE
Change separator to the correct one

### PR DESCRIPTION
**Pull request by dbranco-sdc**
After assigning the login_hint or additional_scopes

### CODE REVIEW

**Comment by greenpau** [comment]
@dbranco-sdc , thank you for contributing 👍 Is this ready to be merged?

P.S. Please avoid unicode drawings in commit messages 😄

**Comment by dbranco-sdc** [comment]
> @dbranco-sdc , thank you for contributing 👍 Is this ready to be merged?
> 
> P.S. Please avoid unicode drawings in commit messages 😄

Yes this is ready, we are already using it from ourselves while waiting for the official release and it is working as expected, in the other hand we have added some tests in order to avoid errors related to this in the future.

About the emojis, sorry I usually use the gitmoji enabled, sorry for that, do you need to me to update the commit message and overwrite it?

By the way this pull request fix the following issue https://github.com/greenpau/go-authcrunch/issues/23

**Comment by dbranco-sdc** [comment]
> > Yes this is ready, we are already using it from ourselves while waiting for the official release and it is working as expected, in the other hand we have added some tests in order to avoid errors related to this in the future.
> 
> @dbranco-sdc , awesome! Thank you!
> 
> > About the emojis, sorry I usually use the gitmoji enabled, sorry for that, do you need to me to update the commit message and overwrite it?
> 
> Yes 😄

Hello, I have overwritten the commit messages to remove the emojis.

**Comment by TobiX** [comment]
If anyone wants to test this in Caddy:
```
xcaddy build --with github.com/greenpau/caddy-security=github.com/Inform-Software/caddy-security@v0.0.0-20220818120500-1d29c2044eef
```

**Comment by greenpau** [comment]
I am back from vacation. Will get to it this week.

**Comment by greenpau** [comment]
@TobiX , @dbranco, will release this weekend.

**Pull request merged**
