### PR TITLE
Remove duplicate ReadFileBytes utility code and check for string zero value

### PR DESCRIPTION
**Pull request by pgporada**
Just driving by after reading a Trail of Bits article. Hope this helps.

### CODE REVIEW

**Comment by greenpau** [comment]
@pgporada , thank you very much! Will take a look at it!

**Comment by pgporada** [comment]
@greenpau Mind taking a look? :)

**Comment by greenpau** [comment]
@pgporada , on it!

**Comment by greenpau** [comment]
@pgporada , please add CLA. 
https://github.com/greenpau/go-authcrunch/blob/main/CONTRIBUTING.md#contributor-license-agreements

**Comment by greenpau** [comment]
@pgporada , thank you for contributing!

**Pull request merged**
